stages:
  process_data:
    cmd: Rscript src\process_data.R
    deps:
    - src\process_data.R
    - src\helpers
    - data\raw
    params:
    - par.yaml:
        - rounds_num_fixed
    outs:
    - data\processed\returns.RDS
    - data\processed\returns_list.RDS
    - data\processed\leaderboard.RDS
    - data\processed\positions_list.RDS
    - data\processed\positions_all_list.RDS
  estimate_coefficients:
    cmd: Rscript src\estimate_coefficients.R
    deps:
    - src\estimate_coefficients.R
    - src\helpers
    - data\processed
    params:
    - par.yaml:
        - participants_num_fixed
        - returns_num_fixed
        - rounds_num_fixed
        - rep_estimate_coefficients
    metrics:
    - outputs\metrics\coefficients.yaml:
        cache: false
  compute_strategy:
    cmd: Rscript src\compute_strategy.R
    deps:
    - src\compute_strategy.R
    - src\helpers
    - outputs\metrics\coefficients.yaml
    params:
    - par.yaml:
        - rounds_num
        - days_per_round
        - returns_num
        - returns_mean
        - rep_compute_strategy
    outs:
    - models\strategy_q_1.RDS
    - models\strategy_q_20.RDS
  run_competition_simulated:
    cmd: Rscript src\run_competition_simulated.R
    deps:
    - src\run_competition_simulated.R
    - src\helpers
    - outputs\metrics\coefficients.yaml
    - models\strategy_q_1.RDS
    - models\strategy_q_20.RDS
    params:
    - par.yaml:
    outs:
    - models\participant_rank_simulated.RDS
    - models\participant_state_simulated.RDS
    - models\participant_beta_simulated.RDS
  run_competition_bootstrapped:
    cmd: Rscript src\run_competition_bootstrapped.R
    deps:
    - src\run_competition_bootstrapped.R
    - src\helpers
    - outputs\metrics\coefficients.yaml
    - models\strategy_q_1.RDS
    - models\strategy_q_20.RDS
    - data\processed\returns_list.RDS
    - data\processed\leaderboard.RDS
    params:
    - par.yaml:
    outs:
    - models\participant_rank_bootstrapped.RDS
    - models\participant_state_bootstrapped.RDS
  test_IR_level:
    cmd: Rscript src\test_IR_level.R
    deps:
    - src\test_IR_level.R
    - src\helpers\simulate_returns.R
    - src\helpers\position_baseline.R
    - src\helpers\WYY.R
    - outputs\metrics\coefficients.yaml
    params:
    - par.yaml:
        - returns_mean
    outs:
    - models\test_IR_level.RDS
  test_IR_pvalue:
    cmd: Rscript src\test_IR_pvalue.R
    deps:
    - src\test_IR_pvalue.R
    - src\helpers\WYY.R
    - data\processed\returns_list.RDS
    - data\processed\positions_list.RDS
    outs:
    - outputs\tables\test_IR_pvalue_table.csv
  submission_analysis:
    cmd: Rscript src\submission_analysis.R
    deps:
    - src\submission_analysis.R
    - src\helpers\compute_round.R
    - data\processed\returns_list.RDS
    - data\processed\positions_all_list.RDS
    outs:
    - outputs\plots\submission_analysis_long.png
    - outputs\plots\submission_analysis_long_rank_diff.png
    - outputs\plots\submission_analysis_rank_long.png
    - outputs\tables\submission_analysis_median_prob.csv
    - outputs\plots\submission_analysis_rank_skew.png
  auxiliary:
    cmd:
    - Rscript src\auxiliary\leaderboard_comparison.R
    - Rscript src\auxiliary\strategy_diagram.R
    - Rscript src\auxiliary\scaling_effects.R
    - Rscript src\auxiliary\position_effects.R
    - Rscript src\auxiliary\competition_statistics_simulated.R
    - Rscript src\auxiliary\competition_statistics_bootstrapped.R
    - Rscript src\auxiliary\test_IR_level_table.R
    deps:
    - src
    - data\processed
    - models
    - outputs\metrics
    params:
    - par.yaml:
    outs:
    - outputs\tables\leaderboard_comparison.csv:
        cache: false
    - outputs\tables\state_table_simulated_tangency.csv:
        cache: false
    - outputs\tables\state_table_simulated_rank_optimization.csv:
        cache: false
    - outputs\tables\state_table_bootstrapped.csv:
        cache: false
    - outputs\tables\test_IR_level_table_asy.csv:
        cache: false
    - outputs\tables\test_IR_level_table_wb.csv:
        cache: false
    plots:
    - outputs\plots\strategy_diagram_q_1.png
    - outputs\plots\strategy_diagram_q_20.png
    - outputs\plots\scaling_effects.png
    - outputs\plots\position_effects.png
    - outputs\plots\rank_histogram_simulated.png
    - outputs\plots\rank_histogram_bootstrapped.png